spring:
  application:
    name: SmartCart
  datasource:
    url: jdbc:postgresql://localhost:5432/smartcart
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

server:
  servlet:
    context-path: /api/v1
  port: 8080

jwt:
  secret: jhgjopukhgnolu876767890p0377iyjhj406712u3uerhijkduyvyhjbnmo
  expiration: 86400000